// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConditionsController from "./conditions_controller"
application.register("conditions", ConditionsController)

import FireworksController from "./fireworks_controller"
application.register("fireworks", FireworksController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ListController from "./list_controller"
application.register("list", ListController)

import MapController from "./map_controller"
application.register("map", MapController)

import ProfilController from "./profil_controller"
application.register("profil", ProfilController)

import SigninShelterController from "./signin_shelter_controller"
application.register("signin-shelter", SigninShelterController)
